# Key - Value  pliik p?aski z rozszerzeniem properti
# Rozszerzenie YAML!
spring:
  h2.console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:./iae-db'
  jpa:
    hibernate:
      ddl-auto: update

